FROM resin/rpi-raspbian:jessie
LABEL Maintainer="jfrandberg@gmail.com" \
      Description="Mosquitto MQTT client based on resin/raspbian"

# Install mqtt client
ENV MOSQUITTO_VERSION=""
RUN apt-get update && \
    apt-get install mosquitto-clients

# Setup handy shortcuts
RUN ln -s /usr/bin/mosquitto_pub /usr/local/bin/pub && \
    ln -s /usr/bin/mosquitto_sub /usr/local/bin/sub


